AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  spring-cloud-function-sample

  Sample SAM Template for spring-cloud-function-sample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    AutoPublishAlias: live
    Timeout: 30
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    Runtime: java11
    Architectures:
      - arm64
    MemorySize: 512
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/

Parameters:
  EnvType:
    Description: Environment type, affect resources creation and Spring active profiles.
    Default: uat
    Type: String
    AllowedValues:
      - uat
      - prod
    ConstraintDescription: must specify uat or prod.

Resources:
  HelloWorldFunction1:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: HelloWorldFunction1
      CodeUri: HelloWorld1/build/libs/HelloWorld1-0.0.1-SNAPSHOT-aws.jar
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref EnvType

  HelloWorldFunction2:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: HelloWorldFunction2
      CodeUri: HelloWorld2/build/libs/HelloWorld2-0.0.1-SNAPSHOT-aws.jar
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref EnvType

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction1:
    Description: "Hello World Lambda Function 1 ARN"
    Value: !GetAtt HelloWorldFunction1.Arn
  HelloWorldFunction2:
    Description: "Hello World Lambda Function 2 ARN"
    Value: !GetAtt HelloWorldFunction2.Arn
  HelloWorldFunction1IamRole:
    Description: "Implicit IAM Role created for Hello World 1 function"
    Value: !GetAtt HelloWorldFunction1Role.Arn
  HelloWorldFunction2IamRole:
    Description: "Implicit IAM Role created for Hello World 2 function"
    Value: !GetAtt HelloWorldFunction2Role.Arn
